swagger: "2.0"
info:
  title: MovieAPI
  description: "Get the trending movies."
  version: "1.0.0"
host: 35.196.176.214
schemes:
  - "https"
paths:
  "/":
    get:
      description: "Get the trending movies."
      operationId: "trendingMovies"
      x-google-backend:
        address: https://movie-api-service-hjxhfq3yba-ue.a.run.app
      responses:
        200:
          description: "Success."
          schema:
            type: string
        400:
          description: "The data cannot be fetched."
